version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: root
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 20
      runas: root
    - location: scripts/docker_up.sh
      timeout: 20
      runas: root
    - location: scripts/db_rake.sh
      timeout: 20
      runas: root
runas: ec2-user
